Immobilier\ManagerBundle\Entity\Localite:
    type: entity
    table: localite
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 200
            fixed: false
            nullable: false
    manyToOne:
        idDelegation:
            targetEntity: Delegation
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_delegation:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
